PERSISTENCE_HOST=localhost;
PERSISTENCE_PORT=5432;
PERSISTENCE_USER=postgres;
PERSISTENCE_PASSWORD=changeme;
PERSISTENCE_DB=reference;
PERSISTENCE_SCHEMA=auth;

APPLICATION_IMAGE_NAME=dotnet-reference-authorization;
APPLICATION_CONTAINER_NAME=dotnet-reference-authorization;
APPLICATION_PORT=16420;
