PERSISTENCE_HOST=localhost;
PERSISTENCE_PORT=5432;
PERSISTENCE_USER=postgres;
PERSISTENCE_PASSWORD=changeme;
PERSISTENCE_DB=referencefile;
PERSISTENCE_SCHEMA=file;

APPLICATION_IMAGE_NAME=dotnet-reference-file;
APPLICATION_CONTAINER_NAME=dotnet-reference-file;
APPLICATION_PORT=16421;
